// <auto-generated />
using System;
using Arma3WebService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arma3WebService.Migrations.SQLite.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Arma3WebService.DBContext.InternalManagement", b =>
                {
                    b.Property<int>("managementType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.HasKey("managementType");

                    b.ToTable("InternalManagement");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerIdentity", b =>
                {
                    b.Property<string>("profileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("lastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("messageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("modListMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("profileStateStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("profileName");

                    b.ToTable("ServerIdentities");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerInfoTemplate", b =>
                {
                    b.Property<ulong>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("lastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("messageActionPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("messageOfflinePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("messageTemplatePath")
                        .HasColumnType("TEXT");

                    b.HasKey("messageId");

                    b.ToTable("ServerInfoList");
                });
#pragma warning restore 612, 618
        }
    }
}
