// <auto-generated />
using System;
using Arma3WebService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arma3WebService.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Arma3WebService.DBContext.InternalManagement", b =>
                {
                    b.Property<int>("managementType")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<ulong>("messageId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnOrder(1);

                    b.HasKey("managementType");

                    b.ToTable("InternalManagement");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerIdentity", b =>
                {
                    b.Property<string>("profileName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("messageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("modListMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("profileStateStamp")
                        .HasColumnType("bigint");

                    b.HasKey("profileName");

                    b.ToTable("ServerIdentities");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerInfoTemplate", b =>
                {
                    b.Property<ulong>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("messageId"));

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("messageActionPath")
                        .HasColumnType("longtext");

                    b.Property<string>("messageOfflinePath")
                        .HasColumnType("longtext");

                    b.Property<string>("messageTemplatePath")
                        .HasColumnType("longtext");

                    b.HasKey("messageId");

                    b.ToTable("ServerInfoList");
                });
#pragma warning restore 612, 618
        }
    }
}
