@Arma3WebService_HostAddress = http://localhost:5048
@JwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZXcgUHJvZHVjdCIsImp0aSI6ImJlM2U3YTdhLTE0OWQtNGUwMS05MWZkLTYzMzQ4NzgxNjU3ZSIsInJvbGUiOiJBZG1pbiIsIm5hbWVpZCI6Ijg0ZmUwNWUwLTgyYjgtNDFmMS05N2JlLTY1ODAxZTEyMzBlNCIsIm5iZiI6MTc3Mjg4MzEzMSwiZXhwIjoxNzcyODg2NzMxLCJpYXQiOjE3NzI4ODMxMzEsImlzcyI6Imlzc3VlciIsImF1ZCI6IkFkbWluIn0.VtMGObAs-5_XN0wwAmAkBDVLsf8wk6JZqJbL2_v6Hg4
@ServerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJOZXcgUHJvZHVjdCIsImp0aSI6IjNmNjFkNjg1LWQzZmItNGY0Yy05ZjNlLWY5NTVmYjVkN2NiZCIsInJvbGUiOiJHYW1lLVNlcnZlciIsIm5hbWVpZCI6ImJhM2VmZDcwLTNiZGMtNDY0My05NjBlLTYzNjYwZTE5ZmE2ZCIsIm5iZiI6MTc3Mjg4MzE0OCwiZXhwIjoxNzcyODg2NzQ4LCJpYXQiOjE3NzI4ODMxNDgsImlzcyI6Imlzc3VlciIsImF1ZCI6IkdhbWUtU2VydmVyIn0.2DYuEYVx6hBHmF8YmK5iUkFz3XTD6v2PXxeX5hkaeVc

GET {{Arma3WebService_HostAddress}}/api/arma/GetLogs/
Accept: application/json
Authorization: Bearer {{JwtToken}} 
###

GET {{Arma3WebService_HostAddress}}/api/token
Content-Type: application/json
{
    "Name": "New",
    "Role": 1,
    "AuthToken": "{{JwtToken}}"
}

###

POST {{Arma3WebService_HostAddress}}/api/token
Content-Type: application/json
{
    "Name": "New Product",
    "Role": 2
}
###

GET {{Arma3WebService_HostAddress}}/api/ws/ingame?access_token={{JwtToken}} 
Accept: application/json
# Authorization: Bearer {{JwtToken}} 

##
