// <auto-generated />
using System;
using Arma3WebService.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arma3WebService.Migrations.NpgSQL.Models
{
    [DbContext(typeof(ServiceDbContext))]
    partial class ServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arma3WebService.DBContext.InternalManagement", b =>
                {
                    b.Property<int>("managementType")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<decimal>("messageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnOrder(1);

                    b.HasKey("managementType");

                    b.ToTable("InternalManagement");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerIdentity", b =>
                {
                    b.Property<string>("profileName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("lastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("messageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("modListMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("profileStateStamp")
                        .HasColumnType("bigint");

                    b.HasKey("profileName");

                    b.ToTable("ServerIdentities");
                });

            modelBuilder.Entity("Arma3WebService.DBContext.ServerInfoTemplate", b =>
                {
                    b.Property<decimal>("messageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("lastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("messageActionPath")
                        .HasColumnType("text");

                    b.Property<string>("messageOfflinePath")
                        .HasColumnType("text");

                    b.Property<string>("messageTemplatePath")
                        .HasColumnType("text");

                    b.HasKey("messageId");

                    b.ToTable("ServerInfoList");
                });
#pragma warning restore 612, 618
        }
    }
}
